spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

#    cache:
#      type: caffeine
#    caffeine:
#      spec: maximumSize = 100

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

    properties:
      hibernate:
        format_sql: true

server:
  port: 9090