server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver

    cache:
      type: caffeine
    caffeine:
      spec: maximumSize = 100

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect